blueprint:
  name: Better Thermostat Day/Night mode
  description: Set BT Thermostats to day/night mode based on night schedule.
  domain: automation
  source_url: https://github.com/fatino/home-assistant/blob/master/blueprints/bt_day_night_mode.yaml
  input:
    night_times_schedule:
      name: Schedule helper
      selector:
        entity:
          domain: schedule

    thermostat_target:
      name: Thermostats
      selector:
        target:
          device:
            integration: better_thermostat
          entity:
            integration: better_thermostat
            domain: climate

    night_temp:
      name: Night Temperature
      description: The target temperature at night
      default: 18
      selector:
        number:
          min: 5
          max: 35
          unit_of_measurement: °C
    
    day_temp:
      name: Day Temperature
      description: The target temperature at day
      default: 21
      selector:
        number:
          min: 5
          max: 35
          unit_of_measurement: °C          

mode: queued
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input night_times_schedule
    from: "on"
    to: "off"
  - platform: state
    entity_id: !input night_times_schedule
    from: "off"
    to: "on"
condition: []
action:
  - if:
      - condition: state
        entity_id: !input night_times_schedule
        state: "on"
    then:
      - service: better_thermostat.set_temp_target_temperature
        data:
          temperature: !input night_temp
        target: !input thermostat_target
    else:
      - service: better_thermostat.set_temp_target_temperature
        data:
          temperature: !input day_temp
        target: !input thermostat_target
